version: "3.10"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Todolist:/Todolist/Todolist
      - ./Todolist/staticfiles:/Todolist/staticfiles
      - ./django_media:/Todolist/django_media

  front:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://api:8080/
