version: "3.10"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: cr0un/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Todolist:/app/Todolist
      - ./Todolist/staticfiles:/Todolist/staticfiles
      - ./django_media:/Todolist/django_media

  front:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    depends_on:
      api:
        condition: service_started
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://api:80/








