version: "3.10"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: cr0un/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    build:
      context: .
    ports:
      - 8000:80
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Todolist:/app/Todolist
      - ./Todolist/staticfiles:/Todolist/staticfiles
      - ./django_media:/Todolist/django_media

  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Todolist:/app/Todolist
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"

  front:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://api:8000/








