version: "3.10"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./Todolist:/Todolist/Todolist
      - ./core:/Todolist/core
      - ./goals:/Todolist/goals
      - django_static:/Todolist/static

  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

  bot:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - ./bot:/todolist/bot
    command: python ./manage.py runbot

volumes:
  todolist_pg_data:
    driver: local
  django_static:
    driver: local